# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:latest

jobs:

  #------------------------------------------------------------
  # 1. Install dependencies
  #------------------------------------------------------------

  install-dependencies:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps

      - run:
          name: 'Install yarn dependencies'
          command: yarn --frozen-lockfile --non-interactive

      - run:
          name: 'Install s3deploy'
          command: curl -L https://github.com/bep/s3deploy/releases/download/v2.3.2/s3deploy_2.3.2_Linux-64bit.tar.gz | tar xvz

      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
            - s3deploy

  #------------------------------------------------------------
  # 2. Build VuePress
  #------------------------------------------------------------

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: 'Run build'
          command: yarn docs:build
      - run:
          name: 'Copy resume pdf into dist'
          command: cp Ethan_Anderson_Resume.pdf docs/.vuepress/dist/
      - persist_to_workspace:
          root: ~/project
          paths:
            - docs/.vuepress/dist

  #------------------------------------------------------------
  # 3. Deploy to S3
  #------------------------------------------------------------

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: 'Deploy to S3'
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              cd ~/project/docs/.vuepress/dist
              ~/project/s3deploy -region=us-east-1 -bucket=www.ethanaa.com -distribution-id=E272FZWDOFIWKK -v
            else
              echo "Non-master branch: dry run only"
              echo
              echo "Working directory files:"
              pwd
              echo
              ls -lAF
              cd ~/project/docs/.vuepress/dist
              echo "Built files:"
              pwd
              echo
              ls -lAF
              echo
              ~/project/s3deploy -region=us-east-1 -bucket=www.ethanaa.com -distribution-id=E272FZWDOFIWKK -v -try
            fi

#------------------------------------------------------------
# Workflows
#------------------------------------------------------------

workflows:
  version: 2
  build:
    jobs:
      - install-dependencies
      - build: { requires: [install-dependencies] }
      - deploy: { requires: [build] }
